AllCops:
  Excludes:
    - bin/*
    - templates/*
    - db/schema.rb
    - features/step_definitions/email_steps.rb
    - config/initializers/i18n-tasks.rb
Documentation:
  Enabled: false

LeadingCommentSpace:
  Enabled: false

LineLength:
  Enabled: false
